### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by nozimm** [cristianmiranda/mediabox#14]
install on ubuntu 20 without errors,
after opening the url in the browser all i get is 404

**Comment by cristianmiranda** [comment]
Hi. What's the URL you're trying to access?
Could you also run this command and paste the output please? `docker logs traefik`

**Comment by cristianmiranda** [comment]
@nozimm I just extracted `traefik` service to a different compose file (`docker-compose.traefik.yml`). If you're not using a custom domain please try to start the stack without that.
```bash
# Main stack + Unprotected Torrenting
docker-compose -f docker-compose.yml -f docker-compose.torrents.yml up -d
```
And then, on your browser, go to `http://localhost:8112` (you should see Deluge's Web UI).

**Comment by nozimm** [comment]
The Problem was, that my server was only accessable through a custom subdomain. I tried it with another domain and not a subdomain, now it works. Thanks.

**Comment by cristianmiranda** [comment]
Excellent! I'm glad it's working now.
