### ISSUE TITLE
Any plans for rclone?

### ISSUE THREAD

**Issue by mandal-rahul** [cristianmiranda/mediabox#19]
Loved your mediabox, Are you planning on adding rclone or something similar to mount with Gdrive? You can keep this optional like your deluge+VPN

**Comment by cristianmiranda** [comment]
Hey! Thanks!. Yes, I'm very interested in replacing my current [overGrive](https://www.thefanclub.co.za/overgrive) setup with a docker container. Would you recommend rclone for this? 
If you feel like it, you could create a PR. I'd love for people to start collaborating on this project. What do you think?.
